version: "3"

services:
  inctrak_goals:
    image: bobcalypsoweb:latest
    expose:
      - 80
    restart: always
    environment:
      VIRTUAL_HOST: bobcalypso.com,www.bobcalypso.com
      LETSENCRYPT_HOST: bobcalypso.com,www.bobcalypso.com
      LETSENCRYPT_EMAIL: calypsosystemsllc@gmail.com
    container_name: bobcalypsoweb

networks:
  default:
    external:
      name: nginx-proxy

